sudo: false

before_install:
- npm install -g grunt-cli
install:
- npm install -d -q
- webdriver-manager update
script:
- grunt travis

branches:
  except:
  - gh-pages

addons:
  sauce_connect: true

env:
  global:
    - secure: O+vzg0XcosbKiMeykEf8w/nhNDTq1zENmmOamZUao4dJfn0st6sjBayLyxvNz5wr1ceix/OrvXmNUxf1iWUZZiDAaVgYhA7TAe/Gdhy0oG95ycHDbDuLGekpBiRfPpRvmB9lR4v2ute+I7naRs/MUttcIe3y2U2/QHJy88E6Dk8=
    - secure: BNbtsy7tA9DgrmjvI4UQ4jCFtxNZkuGZinF3SJnoSgTr7S1HnwAMVS+KXQmrZRivXfe0lmfq7+Tq5hcI3xDYGXV1i23T/x/hqouz+v+8ntq/8rOealqo6Ptz10K/yFbhEwtlnxqK2HKDMylAnVBpyz7QiQ7FxuCMyEn370fUsOk=
