before_install:
- npm install -g grunt-cli
install:
- npm install -d -q
- webdriver-manager update
script:
- grunt travis

branches:
  only:
  - master

addons:
  sauce_connect: true

env:
  global:
    - secure: F6RF/FLlJWL74XRtoK+pfTczIT8TC3i40MHLeYRHneqKQwj8KhRfC2bOh33zwU4Jtcy4UKZ/A8fX38AfzXSgCT8DYf9RurrTpu89Gf9LDsL84T9TrS14or+zZXsJkRpgx443UCq+xYwY3K3MpnU5S6sDKDMOw2GXHEEQPv3f1Ik=
    - secure: QeyxvT5XFxlTO1BKwKfZjdQQTM8lI0LuPQGK06pI5YJOAD3LzzulGdwKMEe3oMJ79qqmQQWvgB2dYfs3esCL45SXp+o+Fwfk+Ly2XWBKiLgbqOCUnlD15VwAKCt+M5tStiC3n0o34GVpgNVbsLeG4V3zpsuoo3MePoduy6kWBGE=
