default:
  - 'clean'
  - 'js'
  - 'cssmin'
  - 'copy:build'

js:
  - 'jshint'
  - 'karma:unit'
  - 'uglify:app'

sample:
 - 'connect:open'
 - 'watch'

test:
  - 'karma:unit'

e2eSauce:
 - 'connect:test'
 - 'protractor:sauce'

e2eChrome:
 - 'connect:test'
 - 'protractor:chrome'

testBrowser:
  - 'karma:browser'

production:
  - 'default'

travis:
 - 'production'
 - 'e2eSauce'

package:
 - 'production'
 - 'e2eChrome'

install:
  - 'shell'

# update library dependencies (ng and ng-mock)
update:
 - 'bower'
 - 'copy:update'




#testSauce:
#  - 'connect:test'
#  - 'protractor:sauce'
